#!/bin/bash

message=$1

npm run lint 
status=$?
if [ "$status" != 0 ]; then 
  echo -e "Erro no lint"
  exit $status
fi

npm test
status=$?
if [ "$status" != 0 ]; then 
  echo -e "Erro no test"
  exit $status
fi



git add .
git commit -m "$message"
git push


source .env
sshpass -p $PASSWORD ssh -t root@128.199.12.79 "\
  source ~/.nvm/nvm.sh &&\
  cd projects/nest-api &&\
  git pull &&\
  npm i &&\
  npm run build &&\
  pm2 restart nest-api --update-env
"